site_name: CMS EGamma POG
site_url: https://cms-egamma.github.io/

theme: readthedocs

nav:
    - e/Î³ POG: index.md
    - Run2:
      - JSONs: EgammaSFJSON.md
      - Recommendations: Run2.md
    - Run3:
      - Person Power: Run3_ID.md
    - Physics Results: PhysicsResults.md
    - Tools: Tools.md
    - FAQs: FAQs.md
    - Attend POG Meetings: https://indico.cern.ch/category/1305/
    - Contact us: Contact.md
theme:
  name: material
  logo: https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/RetrieveFile?docid=3045&filename=CMSlogo_color_nolabel_1024_May2014.png&version=3
